# Generated by Django 5.2.6 on 2025-09-13 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='car_db',
            fields=[
                ('car_id', models.IntegerField(primary_key=True, serialize=False)),
                ('brand', models.CharField(max_length=10)),
                ('model_car', models.CharField(max_length=10)),
                ('purchase_date', models.DateField()),
            ],
        ),
    ]
