# Generated by Django 5.2.6 on 2025-09-13 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ormapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car_db',
            name='mileage',
            field=models.FloatField(default=0),
        ),
    ]
